version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version
      - pip3 install --upgrade awscli
      - npm install -g gulp@3.9.1
      - npm install gulp --save-dev
  post_build:
    commands:
      # Install runtime dependencies
      - npm run build

      # Do not remove thi statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN in template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
artifacts:
  type: zip
  files:
    - template.yml
    - README.md
    - package.json
    - config.js
    - tasks/*
    - gulpfile.js
    - node_modules/**/*
    - lib/**/*
    - clinet/**/*
    - template-configuration.json
    - appspec.yml
    - scripts/*
